"""menu upd

Revision ID: 02650ee52d77
Revises: 308debfc0351
Create Date: 2019-05-17 11:28:46.125466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02650ee52d77'
down_revision = '308debfc0351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_field')
    # ### end Alembic commands ###
