"""¨sd¨

Revision ID: 3232e2e30ed7
Revises: 4ad1f8280e00
Create Date: 2019-07-01 10:12:08.797005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3232e2e30ed7'
down_revision = '4ad1f8280e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_media', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_media', 'label')
    # ### end Alembic commands ###
