"""section display is added

Revision ID: 3d809acc3851
Revises: 5d0304dc4d5c
Create Date: 2019-11-18 15:14:19.349386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d809acc3851'
down_revision = '5d0304dc4d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('display', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'display')
    # ### end Alembic commands ###
