"""add file_type

Revision ID: 5d0304dc4d5c
Revises: 62e88576444b
Create Date: 2019-11-04 18:08:58.827212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0304dc4d5c'
down_revision = '62e88576444b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('file_type', sa.Unicode(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'file_type')
    # ### end Alembic commands ###
