"""init

Revision ID: 62e88576444b
Revises: 
Create Date: 2019-11-04 12:50:51.873693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e88576444b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Unicode(length=255), nullable=True),
    sa.Column('textArea', sa.Unicode(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('encrypted_filename', sa.Unicode(length=255), nullable=True),
    sa.Column('filename', sa.Unicode(length=255), nullable=True),
    sa.Column('link', sa.Unicode(length=255), nullable=True),
    sa.Column('picture', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Unicode(length=64), nullable=True),
    sa.Column('first_name', sa.Unicode(length=64), nullable=True),
    sa.Column('last_name', sa.Unicode(length=64), nullable=True),
    sa.Column('password', sa.Unicode(length=255), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_path', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Unicode(length=64), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('display', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('link', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('assigner_id', sa.Integer(), nullable=True),
    sa.Column('acceptor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Unicode(length=32), nullable=True),
    sa.ForeignKeyConstraint(['acceptor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_timestamp'), 'tasks', ['timestamp'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('page_field_connection',
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], )
    )
    op.create_table('profile_field_connection',
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], )
    )
    op.create_table('profile_template_field_connection',
    sa.Column('profile_template_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['profile_template_id'], ['profile_template.id'], )
    )
    op.create_table('section_field_connection',
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], )
    )
    op.create_table('task_field_connection',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], )
    )
    op.create_table('task_template_field_connection',
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['task_templates.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_template_field_connection')
    op.drop_table('task_field_connection')
    op.drop_table('section_field_connection')
    op.drop_table('profile_template_field_connection')
    op.drop_table('profile_field_connection')
    op.drop_table('page_field_connection')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_tasks_timestamp'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('profiles')
    op.drop_table('pages')
    op.drop_table('menu_fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('task_templates')
    op.drop_table('sections')
    op.drop_table('roles')
    op.drop_table('profile_template')
    op.drop_table('media')
    # ### end Alembic commands ###
