"""templates

Revision ID: 9c9b576de890
Revises: 02650ee52d77
Create Date: 2019-05-17 12:59:37.809117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9b576de890'
down_revision = '02650ee52d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('text', sa.String(length=140), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_field')
    op.drop_table('task_templates')
    # ### end Alembic commands ###
