"""link and picture added

Revision ID: b3152909d137
Revises: 8304b413ad2b
Create Date: 2019-05-21 13:20:41.158414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3152909d137'
down_revision = '8304b413ad2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_media', sa.Column('link', sa.String(length=50), nullable=True))
    op.add_column('task_media', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_media', 'picture')
    op.drop_column('task_media', 'link')
    # ### end Alembic commands ###
