"""number field is added

Revision ID: dda2b53daf25
Revises: daf8b3965022
Create Date: 2019-11-21 12:16:55.329862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda2b53daf25'
down_revision = 'daf8b3965022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'number')
    # ### end Alembic commands ###
